name: AutoWalls
main: com.jkush321.com.jkush321.autowalls.AutoWalls
version: 1.0
commands:
  com.jkush321.autowalls:
    description: Display version and reload config.
  join:
    description: Joins a team
  leave:
    description: Leaves your team
  playing:
    description: Who is playing
  time:
    description: Time left before walls drop
  team:
    description: See whos on your team
  tp:
    description: Teleport to player
  priority:
    description: Gives priority
    aliases: [pri]
  tpplayers:
    description: Teleports players to you
  tpspecs:
    description: Teleports spectators to you
  tpall:
    description: Teleports everyone to you
  tphere:
    description: Teleports everyone to you
  teamchat:
    description: Toggles team chat
    aliases: [tc]
  tell:
    description: Sends a private message
    aliases: [t]
  me:
    description: Used to describe what you're doing
  forcestart:
    description: Only used when necessary
  day:
    description: Sets it to daytime
  night:
    description: Sets it to night
  yell:
    description: Yells outloud
  forcedrop:
    description: Force drops the walls
  forceend:
    descritpion: Ends the round
  fly:
    description: Lets you soar accross la sky
  kit:
    description: Lets you choose a kit
  prefix:
    description: Set a player prefix
permissions:
  walls.player:
    description: Player of walls
    default: true
  walls.op:
    description: Operator of walls
    default: op
  walls.mod:
    description: Moderator of the walls
    default: false